# Generated by Django 4.2.6 on 2023-11-03 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("truthtaste", "0003_alter_storebox_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="storebox",
            name="author",
            field=models.CharField(default="Emily", max_length=50),
        ),
        migrations.AddField(
            model_name="storebox",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="storebox",
            name="image",
            field=models.ImageField(upload_to="restaurant/"),
        ),
        migrations.AlterField(
            model_name="storebox",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
