# Generated by Django 4.2.6 on 2023-11-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "truthtaste",
            "0004_storebox_author_storebox_date_alter_storebox_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="storebox",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="truthtaste.storebox",
                    ),
                ),
            ],
        ),
    ]
