# Generated by Django 4.2.6 on 2023-11-03 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("truthtaste", "0005_alter_storebox_date_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="storebox",
            name="author",
            field=models.CharField(max_length=50),
        ),
    ]
