# Generated by Django 4.2.6 on 2023-11-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("truthtaste", "0006_review_author_alter_storebox_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
