# Generated by Django 4.2.6 on 2023-11-03 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("truthtaste", "0007_review_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storebox",
            name="score",
        ),
    ]
